spring:
  application:
    name: purchase-approve-system
  datasource:
    url: jdbc:mysql://localhost:3306/javatask?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 58888


mybatis-plus:
  type-aliases-package: abc.zyf.purchaseapprovesystem.domain.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: input
      field-strategy: ignored

snowflake:
  worker-id: 1
  datacenter-id: 1

minio:
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: purchaseapprove
  endpoint: http://localhost:9005
  readPath: http://localhost:9005

