package abc.zyf.purchaseapprovesystem.domain.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@AllArgsConstructor
@Data
public class ApprovalRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_record.id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_record.request_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private Long requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_record.approval_step
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     * 1部门经理审批  2财务审批  3总经理审批
     */
    private Integer approvalStep;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_record.id
     *
     * @return the value of approval_record.id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_record.id
     *
     * @param id the value for approval_record.id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_record.request_id
     *
     * @return the value of approval_record.request_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Long getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_record.request_id
     *
     * @param requestId the value for approval_record.request_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setRequestId(Long requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_record.approval_step
     *
     * @return the value of approval_record.approval_step
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Integer getApprovalStep() {
        return approvalStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_record.approval_step
     *
     * @param approvalStep the value for approval_record.approval_step
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setApprovalStep(Integer approvalStep) {
        this.approvalStep = approvalStep;
    }
}