package abc.zyf.purchaseapprovesystem.domain.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@NoArgsConstructor
@AllArgsConstructor
@Data
public class ApprovalRecordDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_record_detail.id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_record_detail.approval_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private Long approvalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_record_detail.approver_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private Long approverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_record_detail.approver_name
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private String approverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_record_detail.approval_result
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private Integer approvalResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_record_detail.approval_opinion
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private String approvalOpinion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_record_detail.approval_time
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private Date approvalTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_record_detail.id
     *
     * @return the value of approval_record_detail.id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_record_detail.id
     *
     * @param id the value for approval_record_detail.id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_record_detail.approval_id
     *
     * @return the value of approval_record_detail.approval_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Long getApprovalId() {
        return approvalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_record_detail.approval_id
     *
     * @param approvalId the value for approval_record_detail.approval_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setApprovalId(Long approvalId) {
        this.approvalId = approvalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_record_detail.approver_id
     *
     * @return the value of approval_record_detail.approver_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Long getApproverId() {
        return approverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_record_detail.approver_id
     *
     * @param approverId the value for approval_record_detail.approver_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setApproverId(Long approverId) {
        this.approverId = approverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_record_detail.approver_name
     *
     * @return the value of approval_record_detail.approver_name
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public String getApproverName() {
        return approverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_record_detail.approver_name
     *
     * @param approverName the value for approval_record_detail.approver_name
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setApproverName(String approverName) {
        this.approverName = approverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_record_detail.approval_result
     *
     * @return the value of approval_record_detail.approval_result
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Integer getApprovalResult() {
        return approvalResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_record_detail.approval_result
     *
     * @param approvalResult the value for approval_record_detail.approval_result
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setApprovalResult(Integer approvalResult) {
        this.approvalResult = approvalResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_record_detail.approval_opinion
     *
     * @return the value of approval_record_detail.approval_opinion
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public String getApprovalOpinion() {
        return approvalOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_record_detail.approval_opinion
     *
     * @param approvalOpinion the value for approval_record_detail.approval_opinion
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setApprovalOpinion(String approvalOpinion) {
        this.approvalOpinion = approvalOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_record_detail.approval_time
     *
     * @return the value of approval_record_detail.approval_time
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Date getApprovalTime() {
        return approvalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_record_detail.approval_time
     *
     * @param approvalTime the value for approval_record_detail.approval_time
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setApprovalTime(Date approvalTime) {
        this.approvalTime = approvalTime;
    }
}