package abc.zyf.purchaseapprovesystem.domain.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;


@NoArgsConstructor
@AllArgsConstructor
@Data
public class OrderFile {

    private Long id;


    private Long orderId;


    private Integer fileType;  //1表示pdf，2表示img


    private String fileUrl;


    private Date uploadTime;


    public Long getId() {
        return id;
    }


    public void setId(Long id) {
        this.id = id;
    }


    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_file.order_id
     *
     * @param orderId the value for order_file.order_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_file.file_type
     *
     * @return the value of order_file.file_type
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Integer getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_file.file_type
     *
     * @param fileType the value for order_file.file_type
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setFileType(Integer fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_file.file_url
     *
     * @return the value of order_file.file_url
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_file.file_url
     *
     * @param fileUrl the value for order_file.file_url
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_file.upload_time
     *
     * @return the value of order_file.upload_time
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_file.upload_time
     *
     * @param uploadTime the value for order_file.upload_time
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }
}