package abc.zyf.purchaseapprovesystem.domain.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.Date;


@NoArgsConstructor
@AllArgsConstructor
@Data
public class purchaseOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.request_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private Long requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.total_amount
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.status
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.create_time
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.id
     *
     * @return the value of purchase_order.id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.id
     *
     * @param id the value for purchase_order.id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.request_id
     *
     * @return the value of purchase_order.request_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Long getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.request_id
     *
     * @param requestId the value for purchase_order.request_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setRequestId(Long requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.total_amount
     *
     * @return the value of purchase_order.total_amount
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.total_amount
     *
     * @param totalAmount the value for purchase_order.total_amount
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.status
     *
     * @return the value of purchase_order.status
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.status
     *
     * @param status the value for purchase_order.status
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.create_time
     *
     * @return the value of purchase_order.create_time
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.create_time
     *
     * @param createTime the value for purchase_order.create_time
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}