package abc.zyf.purchaseapprovesystem.domain.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@NoArgsConstructor
@AllArgsConstructor
@Data
public class purchaseRequestDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.request_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private Long requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.iteam_name
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private String iteamName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.quantity
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.unit_price
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private BigDecimal unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.total_price
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.applicant_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private Long applicantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.applicant_name
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    private String applicantName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.id
     *
     * @return the value of purchase_request_detail.id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.id
     *
     * @param id the value for purchase_request_detail.id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.request_id
     *
     * @return the value of purchase_request_detail.request_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Long getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.request_id
     *
     * @param requestId the value for purchase_request_detail.request_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setRequestId(Long requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.iteam_name
     *
     * @return the value of purchase_request_detail.iteam_name
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public String getIteamName() {
        return iteamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.iteam_name
     *
     * @param iteamName the value for purchase_request_detail.iteam_name
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setIteamName(String iteamName) {
        this.iteamName = iteamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.quantity
     *
     * @return the value of purchase_request_detail.quantity
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.quantity
     *
     * @param quantity the value for purchase_request_detail.quantity
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.unit_price
     *
     * @return the value of purchase_request_detail.unit_price
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.unit_price
     *
     * @param unitPrice the value for purchase_request_detail.unit_price
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.total_price
     *
     * @return the value of purchase_request_detail.total_price
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.total_price
     *
     * @param totalPrice the value for purchase_request_detail.total_price
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.applicant_id
     *
     * @return the value of purchase_request_detail.applicant_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Long getApplicantId() {
        return applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.applicant_id
     *
     * @param applicantId the value for purchase_request_detail.applicant_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setApplicantId(Long applicantId) {
        this.applicantId = applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.applicant_name
     *
     * @return the value of purchase_request_detail.applicant_name
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public String getApplicantName() {
        return applicantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.applicant_name
     *
     * @param applicantName the value for purchase_request_detail.applicant_name
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setApplicantName(String applicantName) {
        this.applicantName = applicantName;
    }
}