package abc.zyf.purchaseapprovesystem.domain.entity;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.TableField;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.Date;

@NoArgsConstructor
@AllArgsConstructor
@Data
public class PurchaseRequest {

    private Long id;

    private Long applicantId;

    private String applicantName;

    private Integer purchaseTypeId;

    private BigDecimal budgetAmount;

    /**
     *
     * //1表示待审批 2表示审批中 3表示已通过 4表示已驳回
     */
    private Integer status;

    private Date createTime;

    //MP的自动填充，设置更新时自动填充。还需要实现MetaObjectHandler接口
    @TableField(fill = FieldFill.UPDATE)
    private Date updateTime;

    private String remark;

    private Date applyTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getApplicantId() {
        return applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.applicant_id
     *
     * @param applicantId the value for purchase_request.applicant_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setApplicantId(Long applicantId) {
        this.applicantId = applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.applicant_name
     *
     * @return the value of purchase_request.applicant_name
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public String getApplicantName() {
        return applicantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.applicant_name
     *
     * @param applicantName the value for purchase_request.applicant_name
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setApplicantName(String applicantName) {
        this.applicantName = applicantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.purchase_type_id
     *
     * @return the value of purchase_request.purchase_type_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Integer getPurchaseTypeId() {
        return purchaseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.purchase_type_id
     *
     * @param purchaseTypeId the value for purchase_request.purchase_type_id
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setPurchaseTypeId(Integer purchaseTypeId) {
        this.purchaseTypeId = purchaseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.budget_amount
     *
     * @return the value of purchase_request.budget_amount
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public BigDecimal getBudgetAmount() {
        return budgetAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.budget_amount
     *
     * @param budgetAmount the value for purchase_request.budget_amount
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setBudgetAmount(BigDecimal budgetAmount) {
        this.budgetAmount = budgetAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.status
     *
     * @return the value of purchase_request.status
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.status
     *
     * @param status the value for purchase_request.status
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.create_time
     *
     * @return the value of purchase_request.create_time
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.create_time
     *
     * @param createTime the value for purchase_request.create_time
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.update_time
     *
     * @return the value of purchase_request.update_time
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.update_time
     *
     * @param updateTime the value for purchase_request.update_time
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.remark
     *
     * @return the value of purchase_request.remark
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.remark
     *
     * @param remark the value for purchase_request.remark
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.apply_time
     *
     * @return the value of purchase_request.apply_time
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.apply_time
     *
     * @param applyTime the value for purchase_request.apply_time
     *
     * @mbg.generated Thu Sep 18 22:51:42 CST 2025
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }
}